name: Build xonsh bin on Nuitka

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  xonsh-binary-nuitka:
    if: github.repository_owner == 'anki-code'
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    env:
      PYTHON_VER: 3.11
      
    steps:
      - uses: actions/checkout@v6

      - name: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'

      - name: Install packages from apt
        run: |
          uname -a
          sudo apt install -y curl git vim patchelf elfutils binutils-common binutils libffi-dev gcc ccache libpython3.11-dev


      - name: Activate mamba and install packages
        run: |
             pip install -U pip setuptools wheel certifi \
             && pip install '.[full]' ujson pygments prompt_toolkit pyperclip \
             && pip install xontrib-sh xontrib-prompt-starship \
             && pip install git+https://github.com/Nuitka/Nuitka@factory

      - name: Test xonsh
        run: |
             which xonsh \
             && xonsh --version \
             && xonsh -c 'xcontext'

      - name: Nuitka build
        continue-on-error: true
        run: |
             nuitka --version \
             && nuitka \
                  --standalone \
                  --onefile \
                  --static-libpython=yes \
                  --no-deployment-flag=self-execution \
                  --onefile-tempdir-spec='%TEMP%/onefile_%PID%_%TIME%' \
                  --show-progress \
                  --show-scons \
                  --show-modules \
                  --assume-yes-for-downloads \
                  --jobs=2 \
                  --include-package=pip \
                  --include-package=setuptools \
                  --include-package=wheel \
                  --include-package=certifi \
                  --include-package-data=certifi \
                  --include-module=ujson \
                  --include-package=pygments \
                  --include-package=prompt_toolkit \
                  --include-module=pyperclip \
                  --include-module=ctypes \
                  --include-package=ctypes \
                  --include-package=xontrib \
                  --include-module=xontrib.sh \
                  --include-module=xontrib.prompt_starship \
                  /opt/hostedtoolcache/Python/3.11.14/x64/lib/python$PYTHON_VER/site-packages/xonsh

      - name: nuitka-crash-report.xml
        continue-on-error: true
        run: |
          [ -f nuitka-crash-report.xml ] && cat nuitka-crash-report.xml

      - name: Rename binary file
        continue-on-error: true
        run: |
          ls -lah xonsh.bin
          export XONSH_SHOW_TRACEBACK=1
          ./xonsh.bin --version
          ./xonsh.bin -c '2+2'
          ./xonsh.bin -c 'echo 123'
          ./xonsh.bin -c 'import json; json.loads("{}")'
          ./xonsh.bin -c 'print(@.imp.json.loads("{}"))'    
          ./xonsh.bin -c 'print(@.imp.json.loads($(echo "{}")))'

      - name: Get latest release upload URL
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const { data: release } = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            core.setOutput('upload_url', release.upload_url);
            core.setOutput('tag_name', release.tag_name);

      - name: Upload xonsh binary Nuitka to latest release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./xonsh.bin
          asset_name: xonsh.bin
          asset_content_type: application/x-executable
